server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@gang-soldesk-nam.tplinkdns.com:15271:xe
    username: gldj
    password: gldj
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  h2:
    console:
      enabled: true
      
  servlet:    multipart:      enabled: true
      max-file-size: 2MB
      location: C:/WorkSpace/springbootwork/upload/video/  
  security:    oauth2:
      client:
        registration:
          facebook:
            client-id: 388663633306432
            client-secret: f0734b9f497d6d1728a7c8f56846f30c
            scope:
            - public_profile
            - email
  
file:
  path: C:/WorkSpace/springbootwork/upload/
    
